# printWidth: 80 # 80
tabWidth: 2
useTabs: true
semi: true
singleQuote: false
# trailingComma: none # none | es5 | all
bracketSpacing: false # true
# jsxBracketSameLine: false # false
# arrowParens: avoid # avoid | always
